### ISSUE TITLE
Adding a guide for installing a custom Modpack from Curseforge

### ISSUE THREAD

**Issue by Yoshlix** [zaphosting/docs#1065]
### What topic does your proposed suggestion relate to?

Minecraft

### How do you aim to structure your proposed change?

- Step 1 - Downloading the server files for your Modpack
- Step 2 - Extracting the server files from the downloaded file
- Step 3 - Finding the Forge or Fabric version and installing it on your server
- Step 4 - Uploading the server files via FTP on your server

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

- Get the server files from curseforge
- Find the Forge / Fabric version of the modpack
- Install Forge / Fabric on a game server
- Uploading the server files on a server

### What is your ZAP ID?

zap608748

### What is your Discord ID?

698530806167240764

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey there @Yoshlix, thanks for submitting a suggestion issue!

We currently do have a page about installing forge mods (which can be found here: https://zap-hosting.com/guides/docs/minecraft-forge-add-mods) however, it is quite basic.

Since mods and modpacks are essentially similar topics, I believe that it would make the most sense to edit the existing guide with more information, screenshots, and also mentions of modpacks.

I think the following structure would be suitable:
- Step 1 - Finding & downloading mods or modpacks
- Step 2 - Extracting files from downloads
- Step 3 - Installing the correct server version
- Step 4 - Connecting & uploading mods via FTP

You could also add subheadings to **Step 4** to split it between mods and modpacks, if the process is very different, if not you could keep it normal. Perhaps an **Important** admonition may also be userful within **Step 1** to let the reader know that mods have a specific Minecraft Version.

If this sounds good with you, we can approve this 😄

**Comment by Yoshlix** [comment]
Hey, thanks for your nice answer!

It would definitely make sense to write a guide about adding mods and modpacks. I'll start writing the guide within the next few days, but I have one question. 

I could write a German version of the guide, but where would I put it? The English version is clear, just edit the appropriate file in the docs folder. Where are the German files?

**Comment by ThatGuyJacobee** [comment]
Hey again!

That sounds good, no rush on this. About the German version, don't worry about that because we translate it manually ourselves. At the moment, the contribution program only covers English content (we do the translations ourselves). 

So feel free to do everything as normal and submit a PR once you are ready! Of course, if you need any help you can use the contribution guide to follow through, or message us here 👌

Thanks 😇
