### ISSUE TITLE
Installing Javascript / Python Runtimes on Linux

### ISSUE THREAD

**Issue by itscc8** [zaphosting/docs#1119]
### What topic does your proposed suggestion relate to?

I'd like to make 3 new pages on installing Javascript (Node and Deno) and Python on Linux.

### How do you aim to structure your proposed change?

1.  Main install procedure
2. Alternative installs
3. Simple example for running code

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

For Node there are 3 ways to install:
1. Via apt + n package to update
2. Nodesource
3. Nvm

For Deno:
1.  Using curl

For python:
1. It comes pre installed with some distros so I'll also write about making venv and more.

### What is your ZAP ID?

zap473905

### What is your Discord ID?

501132017367384070

### Do you have any previous experience in writing and publishing articles?

Yeah I do. Wrote some articles for zap's docs page :0

### Additional Information

-

### Do you depend on a service for creating your guide?

-

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey there @itscc8,

Could you expand on your idea here? You stated that you would want to create 3 pages, I assume you would want to create one for Node, one for Deno and lastly a 3rd one for Python? (I assume that is what the summary in the issue is meant to state).

I assume that you would want to place these into the following section: "vRootserver->Linux->Services->Install XYZ"?

Ideally, we would like it if you provided the installation instructions for our currently available distros which are Ubuntu, Debian, CentOS, OpenSUSE and Fedora. We had a fellow contributor create a well-structured [guide for databases](https://zap-hosting.com/guides/docs/vserver-linux-databases) which you could have a look at to see potential ways in which you could provide instructions for multiple Linux distros. 👍

Let me know what you think. 🙂

**Comment by ThatGuyJacobee** [comment]
Awesome, this sounds good! By the way, you don't have to strictly use that guide but I think it groups and displays instructions for all of the distros quite nicely so it might fit well in your guides too. 🙂👍

**Comment by itscc8** [comment]
For now I stopped writing because I got a lot on my plate. I guess the issue can be closed and I'll make another referencing this one when I'm ready to continue writing.

**Comment by itscc8** [comment]
Hey👋 I got some free time on my hands would love to start writing these guides. I'll start with nodejs then I'll write the python one.

**Comment by ThatGuyJacobee** [comment]
Hey again @itscc8

Indeed this would be possible. Reading the previous discussions, it would be better if you created one combined guide for Javascript Runtimes, split between Node.js/Deno, and then a second for Python (both for Linux of course).

Good luck!

**Comment by ThatGuyJacobee** [comment]
Sounds good :)

**Comment by itscc8** [comment]
Javascript guide needs more work but will be done soon

**Comment by ThatGuyJacobee** [comment]
Completed 🙂
