### ISSUE TITLE
How to install the Pterodactyl on Linux Server

### ISSUE THREAD

**Issue by nicolasbaud** [zaphosting/docs#1210]
### What topic does your proposed suggestion relate to?

How to install the Pterodactyl on Linux Server

### How do you aim to structure your proposed change?

1. Introduction
2. Installing the panel
3. Installing Wings
4. Create node

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

I will provide all instruction with installation script

### What is your ZAP ID?

zap784106

### Do you have any previous experience in writing and publishing articles?

Yes, I have been writing multiple articles on french documentation

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hi there @nicolasbaud! Thank you for your interest in the Contribution Program. Apologies for the delay as we were discussing your idea in detail. 🙂

Good news, we have decided to accept your suggestion! A Pterodactyl guide would indeed be appropriate for our Dedicated Server section under Linux. The reason this shouldn't be placed under our vRootserver section is because it's generally not advised to run pterodactyl on LXC or KVM virtualised systems as it would be prone to issues.

I would advise you to add a "prerequisites" section at the beginning of the guide to let the reader know what they need to prepare, such as which Linux distros they need to have installed and so on. Lastly, make sure to follow our guidelines so that the content is fit for purpose and well-rounded.

If you have any further questions, feel free to let me know ;) Good luck in creating your content. 🙌
